# Generated by Django 5.2.14 on 2026-05-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0003_affiliate_code_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated on save (format: NAME-XXXX).', max_length=32, unique=True),
        ),
    ]
