# Generated by Django 5.2.7 on 2025-11-18 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='colors/inspirations/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='e.g., OB-202', max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('hex_code', models.CharField(blank=True, help_text='Optional HEX code for display', max_length=7, null=True)),
                ('rgb_value', models.CharField(blank=True, max_length=20, null=True)),
                ('cmyk_value', models.CharField(blank=True, max_length=20, null=True)),
                ('undertone', models.CharField(blank=True, choices=[('warm', 'Warm'), ('cool', 'Cool'), ('neutral', 'Neutral')], max_length=50, null=True)),
                ('lrv', models.DecimalField(blank=True, decimal_places=2, help_text='Light Reflectance Value', max_digits=5, null=True)),
                ('opacity_strength', models.CharField(blank=True, choices=[('weak', 'Weak'), ('medium', 'Medium'), ('strong', 'Strong')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('coverage_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('drying_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('voc_level', models.CharField(blank=True, max_length=50, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='colors/swatches/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colors.colorcollection')),
                ('inspiration_images', models.ManyToManyField(blank=True, related_name='colors', to='colors.colorimage')),
                ('available_finishes', models.ManyToManyField(blank=True, related_name='colors', to='colors.finish')),
                ('recommended_rooms', models.ManyToManyField(blank=True, related_name='colors', to='colors.roomtype')),
                ('recommended_surfaces', models.ManyToManyField(blank=True, related_name='colors', to='colors.surface')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='colors.color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_colors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Color',
                'verbose_name_plural': 'Saved Colors',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'color')},
            },
        ),
    ]
