# Generated by Django 5.2.7 on 2025-12-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='available_finishes',
        ),
        migrations.RemoveField(
            model_name='color',
            name='recommended_surfaces',
        ),
        migrations.RemoveField(
            model_name='color',
            name='coverage_per_liter',
        ),
        migrations.RemoveField(
            model_name='color',
            name='drying_time_hours',
        ),
        migrations.RemoveField(
            model_name='color',
            name='voc_level',
        ),
        migrations.AlterField(
            model_name='color',
            name='lrv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Light Reflectance Value (0-100)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='opacity_strength',
            field=models.CharField(blank=True, choices=[('weak', 'Weak'), ('medium', 'Medium'), ('strong', 'Strong')], help_text='Pigment coverage strength', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Finish',
        ),
        migrations.DeleteModel(
            name='Surface',
        ),
    ]
