# Generated by Django 5.2.7 on 2025-11-18 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('features_colors', models.BooleanField(default=True, help_text='Do products in this category have colors? (e.g. Yes for Paints, No for Tools)')),
                ('features_sizes', models.BooleanField(default=True, help_text='Do products in this category have sizes? (e.g. Yes for Paints, maybe No for Brushes)')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Base price for products without variants (e.g., Tools). Overridden by ProductItem prices if variants exist.', max_digits=10)),
                ('main_image', models.ImageField(blank=True, help_text='The main image for the product. Used if the size variant has no specific image.', null=True, upload_to='products/main/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_colors', models.ManyToManyField(blank=True, help_text='Colors this product is available in.', related_name='products', to='colors.color')),
                ('category', models.ForeignKey(help_text='The main group this product belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('SDS', 'Safety Data Sheet (SDS)'), ('TDS', 'Technical Data Sheet (TDS)'), ('CERT', 'Certification / Compliance Document'), ('GUIDE', 'Application Guide / Brochure'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='products/safety_docs/')),
                ('language', models.CharField(blank=True, help_text='e.g. English, French', max_length=50, null=True)),
                ('version', models.CharField(blank=True, help_text='Document version code', max_length=50, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, help_text='Products this document applies to', related_name='safety_documents', to='products.product')),
            ],
            options={
                'verbose_name': 'Safety Document',
                'verbose_name_plural': 'Safety Documents',
                'ordering': ['doc_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this specific size of the product.', max_digits=10)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, help_text='Optional: Image specific to this size variant. If empty, the main product image is used.', null=True, upload_to='products/items/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_items', to='products.size')),
            ],
            options={
                'verbose_name': 'Product Item (Size Variant)',
                'verbose_name_plural': 'Product Items (Size Variants)',
                'ordering': ['product', 'size'],
                'unique_together': {('product', 'size')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(help_text='Sizes this product is sold in, with price and optional specific image defined in ProductItem.', related_name='products', through='products.ProductItem', to='products.size'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
                'ordering': ['name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Optional specific group (e.g. Interior for Paints). Leave blank for generic items.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.subcategory'),
        ),
        migrations.CreateModel(
            name='SavedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Product',
                'verbose_name_plural': 'Saved Products',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
