# Generated by Django 5.2.7 on 2025-12-28 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
        ('products', '0002_remove_product_sizes_remove_product_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Upload a small icon (SVG or PNG) to display on the product page.', null=True, upload_to='tools/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='safetydocument',
            options={'ordering': ['doc_type', 'title']},
        ),
        migrations.AlterModelOptions(
            name='savedproducts',
            options={'ordering': ['-saved_at'], 'verbose_name': 'Saved Product'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.AddField(
            model_name='product',
            name='coats_required',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='product',
            name='coverage_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coverage in square meters per liter (m2/L).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='drying_time',
            field=models.CharField(blank=True, help_text="e.g. 'Touch dry in 2 hours'.", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='other_products_needed',
            field=models.ManyToManyField(blank=True, help_text='Essential add-ons (e.g. Hardener, Thinner).', related_name='required_by', to='products.product', verbose_name='Other Products Needed'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Optional cross-sells (e.g. Similar paints).', related_name='related_to', to='products.product'),
        ),
        migrations.AlterField(
            model_name='category',
            name='features_colors',
            field=models.BooleanField(default=True, help_text='Check if products in this category come in different colors.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='features_sizes',
            field=models.BooleanField(default=True, help_text='Check if products in this category are sold in different sizes.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='colors.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.subcategory'),
        ),
        migrations.AlterField(
            model_name='safetydocument',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Select all products this document applies to.', related_name='safety_documents', to='products.product'),
        ),
        migrations.AlterField(
            model_name='safetydocument',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tools_needed',
            field=models.ManyToManyField(blank=True, help_text='Select tools required for application.', related_name='products', to='products.applicationmethod', verbose_name='Tools Needed'),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.ForeignKey(blank=True, help_text='Sheen level (e.g. Matte, Gloss).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.finish'),
        ),
        migrations.AddField(
            model_name='product',
            name='suitable_surfaces',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.surface'),
        ),
    ]
