# Generated by Django 5.2.7 on 2025-12-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_applicationmethod_finish_surface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coats_required',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
