# Generated by Django 5.2.14 on 2026-05-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_coats_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Product category', 'verbose_name_plural': 'Product categories'},
        ),
    ]
